[project]
name = "MLOps_course_AGH_lab_07"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "onnxruntime",
    "pydantic",
    "fastapi>=0.118.2",
    "uvicorn>=0.37.0",
    "transformers>=4.57.0",
]

